# syntax=docker/dockerfile:1

ARG GO_VERSION=1.24
ARG BASE_DEBIAN_DISTRO="bullseye"
ARG GOLANG_IMAGE="golang:${GO_VERSION}-${BASE_DEBIAN_DISTRO}"

FROM ${GOLANG_IMAGE} AS base
ARG APT_MIRROR
ARG GOPROXY
ARG SLIM_LDFLAGS
WORKDIR /root/app
RUN sed -ri "s/(httpredir|deb).debian.org/${APT_MIRROR:-deb.debian.org}/g" /etc/apt/sources.list \
 && sed -ri "s/(security).debian.org/${APT_MIRROR:-security.debian.org}/g" /etc/apt/sources.list \
 && sed -ri "s/(snapshot).debian.org/${APT_MIRROR:-snapshot.debian.org}/g" /etc/apt/sources.list \
 && cat /etc/apt/sources.list
RUN git config --global --add safe.directory /root/app

FROM base AS build-env
WORKDIR /root/app
RUN --mount=type=cache,sharing=locked,id=ctrsploit-build-aptlib,target=/var/lib/apt \
    --mount=type=cache,sharing=locked,id=ctrsploit-build-aptcache,target=/var/cache/apt \
    apt update && apt install -y \
    xz-utils \
    jq \
    clang \
    llvm \
    libbpf-dev
ADD https://github.com/upx/upx/releases/download/v5.0.2/upx-5.0.2-amd64_linux.tar.xz /tmp/upx.tar.xz
RUN tar -xf /tmp/upx.tar.xz -C /tmp
RUN --mount=type=bind,target=.,rw \
    --mount=type=cache,target=/root/.cache/go-build,id=ctrsploit-build \
    --mount=type=cache,target=/go/pkg/mod,id=ctrsploit-mod \
    --mount=type=tmpfs,target=/go/src/ \
    GOPROXY=${GOPROXY} go mod download

FROM build-env AS build
RUN --mount=type=bind,target=.,rw \
    --mount=type=cache,target=/root/.cache/go-build,id=ctrsploit-build \
    --mount=type=cache,target=/go/pkg/mod,id=ctrsploit-mod \
    --mount=type=tmpfs,target=/go/src/ \
    make build && mv bin /build

# usage:
# > docker buildx bake binary
# or
# > make binary
FROM scratch AS binary
COPY --from=build /build /

FROM build-env AS shell
ENV GOPROXY=${GOPROXY}
ENV SLIM_LDFLAGS=${SLIM_LDFLAGS}
RUN ln -s /root/app/bin/latest/ctrsploit_linux_amd64 /usr/bin/ctrsploit
