name: service-account-secret-pods
test_envs:
  - name: kubernetes-v1.34.0-calico
    kind: dqd
    dqd_dir: kubernetes/v1.34.0-calico
    pkg: github.com/ctrsploit/ctrsploit/prerequisite/kubernetes/service-account/secret
    cmd: |
      until kubectl wait --for=condition=Ready pod --all -A --timeout=30s; do sleep 10; done
      TEST_ENV=with_secret_access /ctrsploit.test -test.v -test.run "^TestE2E_PodsWithSecretAccess$"
      TEST_ENV=without_secret_access /ctrsploit.test -test.v -test.run "^TestE2E_PodsWithSecretAccess$"
