# Makefile.vars - Variable definitions
# Contains all build and configuration related variable definitions

APP_NAME := ctrsploit

# mirror
DEFAULT_CN_APT_MIRROR := mirrors.tuna.tsinghua.edu.cn
DEFAULT_CN_GOPROXY := https://goproxy.cn,https://goproxy.io,direct
APT_MIRROR ?= $(if $(CN),$(DEFAULT_CN_APT_MIRROR),)
GOPROXY ?= $(if $(CN),$(DEFAULT_CN_GOPROXY),)

# debug
PROGRESS_PLAIN := --progress plain
DEBUG_FLAGS ?= $(if $(DEBUG),$(PROGRESS_PLAIN),)

# ldflags
GIT_COMMIT := $(shell git rev-parse --short HEAD || echo unsupported)
VERSION := $(shell ./script/version.sh)
BUILD_TIME := $(shell date -u +"%Y-%m-%dT%H:%M:%SZ")
SLIM_LDFLAGS ?= -s -w
LDFLAGS := "$(SLIM_LDFLAGS) \
	-X github.com/ctrsploit/sploit-spec/pkg/version.ProductName=${APP_NAME} \
	-X github.com/ctrsploit/sploit-spec/pkg/version.Version=${VERSION} \
	-X github.com/ctrsploit/sploit-spec/pkg/version.GitCommit=${GIT_COMMIT} \
	-X github.com/ctrsploit/sploit-spec/pkg/version.BuildTime=${BUILD_TIME}"

# image
IMAGE_NAME := ghcr.io/ctrsploit/ctrsploit-dev
DEV_IMAGE := $(IMAGE_NAME):$(VERSION)
DOCKERFILE := Dockerfile_dev

# build flags
BUILD_APT_MIRROR := $(if $(APT_MIRROR),--build-arg APT_MIRROR="$(APT_MIRROR)")
BUILD_GO_PROXY := $(if $(GOPROXY),--build-arg GOPROXY="$(GOPROXY)")
BUILD_SLIM_LDFLAGS := $(if $(SLIM_LDFLAGS), --build-arg SLIM_LDFLAGS="$(SLIM_LDFLAGS)")
BUILD_OPTS := ${BUILD_APT_MIRROR} ${BUILD_GO_PROXY} ${BUILD_SLIM_LDFLAGS} ${DOCKER_BUILD_ARGS} ${DOCKER_BUILD_OPTS} -f "$(DOCKERFILE)"

