# Makefile.test - Test related tasks
# Contains unit tests, integration tests and E2E tests

.PHONY: unittest test test.bin e2e

unittest:
	go test -v github.com/ctrsploit/ctrsploit/...

test:
	docker run --rm -v $(CURDIR):/root/app --env TEST_ENV=$(TEST_ENV) $(DEV_IMAGE) make unittest

test.bin:
	mkdir -p bin/test
	docker run --rm -v $(CURDIR):/root/app $(DEV_IMAGE) ./script/test_bin.sh $(PKG)

e2e:
	./test/e2e/e2e.sh $(DIR)

